In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

path = '/content/drive/MyDrive/빅콘테스트/01.데이터수집 및 탐색/data/raw_data/JEJU_MCT_DATA_v2.csv'
df = pd.read_csv(path, encoding='utf-8')
df.head()

,YM,MCT_NM,OP_YMD,MCT_TYPE,ADDR,UE_CNT_GRP,UE_AMT_GRP,UE_AMT_PER_TRSN_GRP,MON_UE_CNT_RAT,TUE_UE_CNT_RAT,...,HR_18_22_UE_CNT_RAT,HR_23_4_UE_CNT_RAT,LOCAL_UE_CNT_RAT,RC_M12_MAL_CUS_CNT_RAT,RC_M12_FME_CUS_CNT_RAT,RC_M12_AGE_UND_20_CUS_CNT_RAT,RC_M12_AGE_30_CUS_CNT_RAT,RC_M12_AGE_40_CUS_CNT_RAT,RC_M12_AGE_50_CUS_CNT_RAT,RC_M12_AGE_OVR_60_CUS_CNT_RAT
0,202301,통큰돼지,20110701,가정식,제주 제주시 용담이동 2682-9번지 통큰돼지,5_75~90%,4_50~75%,3_25~50%,0.161290,0.032258,...,0.838710,0.000000,0.707763,0.610,0.390,0.103,0.124,0.245,0.387,0.142
1,202301,해변,20050407,단품요리 전문,제주 제주시 애월읍 애월리 410-6번지,3_25~50%,2_10~25%,2_10~25%,0.090909,0.121212,...,0.560606,0.000000,0.230928,0.542,0.458,0.221,0.201,0.195,0.244,0.139
2,202301,한그릇,20120919,단품요리 전문,제주 서귀포시 색달동 2315-1번지 한그릇,3_25~50%,3_25~50%,4_50~75%,0.224719,0.112360,...,0.000000,0.000000,0.347059,0.529,0.471,0.138,0.309,0.342,0.164,0.047
3,202301,협재해녀의집,20130627,가정식,제주 제주시 한림읍 협재리 1459-2번지,3_25~50%,3_25~50%,4_50~75%,0.000000,0.271739,...,0.152174,0.000000,0.016096,0.484,0.516,0.323,0.321,0.209,0.109,0.039
4,202301,까망꼬숑,20220826,단품요리 전문,제주 제주시 노형동 3784-12번지 1층,5_75~90%,3_25~50%,2_10~25%,0.272727,0.121212,...,0.727273,0.090909,0.264463,0.513,0.487,0.412,0.311,0.176,0.076,0.025

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67864 entries, 0 to 67863
Data columns (total 28 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   YM                             67864 non-null  int64
 1   MCT_NM                         67864 non-null  object
 2   OP_YMD                         67864 non-null  int64
 3   MCT_TYPE                       67864 non-null  object
 4   ADDR                           67864 non-null  object
 5   UE_CNT_GRP                     67864 non-null  object
 6   UE_AMT_GRP                     67864 non-null  object
 7   UE_AMT_PER_TRSN_GRP            67864 non-null  object
 8   MON_UE_CNT_RAT                 67864 non-null  float64
 9   TUE_UE_CNT_RAT                 67864 non-null  float64
 10  WED_UE_CNT_RAT                 67864 non-null  float64
 11  THU_UE_CNT_RAT                 67864 non-null  float64
 12  FRI_UE_CNT_RAT                 67864 non-null  float64
 13  SAT_UE_CNT_RAT                 67864 non-null  float64
 14  SUN_UE_CNT_RAT                 67864 non-null  float64
 15  HR_5_11_UE_CNT_RAT             67864 non-null  float64
 16  HR_12_13_UE_CNT_RAT            67864 non-null  float64
 17  HR_14_17_UE_CNT_RAT            67864 non-null  float64
 18  HR_18_22_UE_CNT_RAT            67864 non-null  float64
 19  HR_23_4_UE_CNT_RAT             67864 non-null  float64
 20  LOCAL_UE_CNT_RAT               67864 non-null  float64
 21  RC_M12_MAL_CUS_CNT_RAT         67864 non-null  float64
 22  RC_M12_FME_CUS_CNT_RAT         67864 non-null  float64
 23  RC_M12_AGE_UND_20_CUS_CNT_RAT  67864 non-null  float64
 24  RC_M12_AGE_30_CUS_CNT_RAT      67864 non-null  float64
 25  RC_M12_AGE_40_CUS_CNT_RAT      67864 non-null  float64
 26  RC_M12_AGE_50_CUS_CNT_RAT      67864 non-null  float64
 27  RC_M12_AGE_OVR_60_CUS_CNT_RAT  67864 non-null  float64
dtypes: float64(20), int64(2), object(6)
memory usage: 14.5+ MB

In [ ]:
#컬럼명 수정
df = df.rename(columns={
    'YM': '기준연월',
    'MCT_NM' : '가맹점명',
    'OP_YMD' : '개설일자',
    'MCT_TYPE' : '업종',
    'ADDR' : '주소',
    'UE_CNT_GRP' : '이용건수구간',
    'UE_AMT_GRP' : '이용금액구간',
    'UE_AMT_PER_TRSN_GRP' : '건당평균이용금액구간',
    'MON_UE_CNT_RAT' : '월_이용건수비중',
    'TUE_UE_CNT_RAT' : '화_이용건수비중',
    'WED_UE_CNT_RAT' : '수_이용건수비중',
    'THU_UE_CNT_RAT' : '목_이용건수비중',
    'FRI_UE_CNT_RAT' : '금_이용건수비중',
    'SAT_UE_CNT_RAT' : '토_이용건수비중',
    'SUN_UE_CNT_RAT' : '일_이용건수비중',
    'HR_5_11_UE_CNT_RAT' : '05-11시_이용건수비중',
    'HR_12_13_UE_CNT_RAT' : '12-13시_이용건수비중',
    'HR_14_17_UE_CNT_RAT' : '14-17시_이용건수비중',
    'HR_18_22_UE_CNT_RAT' : '18-22시_이용건수비중',
    'HR_23_4_UE_CNT_RAT' : '23-04시_이용건수비중',
    'LOCAL_UE_CNT_RAT' : '현지인_이용건수비중',
    'RC_M12_MAL_CUS_CNT_RAT' : '남성_이용건수비중',
    'RC_M12_FME_CUS_CNT_RAT' : '여성_이용건수비중',
    'RC_M12_AGE_UND_20_CUS_CNT_RAT' : '10-20대_회원비중',
    'RC_M12_AGE_30_CUS_CNT_RAT' : '30대_회원비중',
    'RC_M12_AGE_40_CUS_CNT_RAT' : '40대_회원비중',
    'RC_M12_AGE_50_CUS_CNT_RAT' : '50대_회원비중',
    'RC_M12_AGE_OVR_60_CUS_CNT_RAT' : '60대이상_회원비중'})

In [ ]:
df.columns

Index(['기준연월', '가맹점명', '개설일자', '업종', '주소', '이용건수구간', '이용금액구간', '건당평균이용금액구간',
       '월_이용건수비중', '화_이용건수비중', '수_이용건수비중', '목_이용건수비중', '금_이용건수비중', '토_이용건수비중',
       '일_이용건수비중', '05-11시_이용건수비중', '12-13시_이용건수비중', '14-17시_이용건수비중',
       '18-22시_이용건수비중', '23-04시_이용건수비중', '현지인_이용건수비중', '남성_이용건수비중',
       '여성_이용건수비중', '10-20대_회원비중', '30대_회원비중', '40대_회원비중', '50대_회원비중',
       '60대이상_회원비중'],
      dtype='object')

#기준연월
- 202301~202312

In [ ]:
df['기준연월'].unique()

array([202301, 202302, 202303, 202304, 202305, 202306, 202307, 202308,
       202309, 202310, 202311, 202312])

# 가맹점명
- 기준연월별로 구분하기 때문에 중복가능성 있음
- 1. 같은 가게가 여러개 일수 있음 / 2. 기준연월로 중복

In [ ]:
df['가맹점명'].unique()

array(['통큰돼지', '해변', '한그릇', ..., '버거킹 제주민속오일장DT점', '주식회사 소라 구쟁기가김밥속에 본점',
       '새아침해장국'], dtype=object)

In [ ]:
df['가맹점명'].value_counts()

가맹점명
쭈꾸쭈꾸쭈꾸미    24
뽈살집        24
마리조아       24
황금어장       24
이치진        24
           ..
정성푸드        1
대양회초밥       1
제주창스닥       1
월스낵         1
새아침해장국      1
Name: count, Length: 9252, dtype: int64

In [ ]:
df[df['가맹점명'] == '새아침해장국']

,기준연월,가맹점명,개설일자,업종,주소,이용건수구간,이용금액구간,건당평균이용금액구간,월_이용건수비중,화_이용건수비중,...,18-22시_이용건수비중,23-04시_이용건수비중,현지인_이용건수비중,남성_이용건수비중,여성_이용건수비중,10-20대_회원비중,30대_회원비중,40대_회원비중,50대_회원비중,60대이상_회원비중
67821,202312,새아침해장국,20231120,단품요리 전문,제주 제주시 도련일동 2191-9번지 1층,2_10~25%,3_25~50%,5_75~90%,0.129808,0.0,...,0.0,0.0,0.909091,0.641,0.359,0.03,0.216,0.365,0.21,0.18

In [ ]:
df[df['가맹점명'] == '뽈살집']

,기준연월,가맹점명,개설일자,업종,주소,이용건수구간,이용금액구간,건당평균이용금액구간,월_이용건수비중,화_이용건수비중,...,18-22시_이용건수비중,23-04시_이용건수비중,현지인_이용건수비중,남성_이용건수비중,여성_이용건수비중,10-20대_회원비중,30대_회원비중,40대_회원비중,50대_회원비중,60대이상_회원비중
327,202301,뽈살집,20130321,가정식,제주 제주시 한림읍 한림리 1252-8번지,3_25~50%,1_상위 10% 이하,3_25~50%,0.146789,0.045872,...,0.633028,0.000000,0.119014,0.539,0.461,0.290,0.373,0.177,0.118,0.042
2444,202301,뽈살집,20091224,가정식,제주 서귀포시 서귀동 278-5번지,3_25~50%,2_10~25%,3_25~50%,0.175926,0.148148,...,0.666667,0.018519,0.071161,0.532,0.468,0.304,0.307,0.195,0.142,0.052
8070,202302,뽈살집,20130321,가정식,제주 제주시 한림읍 한림리 1252-8번지,3_25~50%,1_상위 10% 이하,3_25~50%,0.205128,0.059829,...,0.752137,0.000000,0.122449,0.531,0.469,0.293,0.370,0.170,0.125,0.043
11316,202302,뽈살집,20091224,가정식,제주 서귀포시 서귀동 278-5번지,3_25~50%,2_10~25%,3_25~50%,0.186047,0.104651,...,0.546512,0.011628,0.069767,0.532,0.468,0.303,0.303,0.198,0.143,0.052
12948,202303,뽈살집,20130321,가정식,제주 제주시 한림읍 한림리 1252-8번지,3_25~50%,1_상위 10% 이하,3_25~50%,0.156522,0.147826,...,0.817391,0.017391,0.121918,0.540,0.460,0.286,0.375,0.170,0.125,0.044
15281,202303,뽈살집,20091224,가정식,제주 서귀포시 서귀동 278-5번지,3_25~50%,2_10~25%,3_25~50%,0.114286,0.142857,...,0.695238,0.019048,0.072031,0.531,0.469,0.295,0.304,0.200,0.151,0.051
17710,202304,뽈살집,20130321,가정식,제주 제주시 한림읍 한림리 1252-8번지,3_25~50%,2_10~25%,3_25~50%,0.134021,0.082474,...,0.762887,0.000000,0.122708,0.543,0.457,0.285,0.368,0.180,0.125,0.043
20347,202304,뽈살집,20091224,가정식,제주 서귀포시 서귀동 278-5번지,3_25~50%,1_상위 10% 이하,3_25~50%,0.157895,0.140351,...,0.754386,0.026316,0.075203,0.529,0.471,0.298,0.296,0.210,0.149,0.047
23556,202305,뽈살집,20130321,가정식,제주 제주시 한림읍 한림리 1252-8번지,3_25~50%,2_10~25%,3_25~50%,0.108911,0.207921,...,0.801980,0.000000,0.128684,0.530,0.470,0.291,0.356,0.180,0.131,0.042
25591,202305,뽈살집,20091224,가정식,제주 서귀포시 서귀동 278-5번지,3_25~50%,2_10~25%,3_25~50%,0.080000,0.200000,...,0.706667,0.026667,0.075237,0.526,0.474,0.302,0.291,0.205,0.153,0.050
28866,202306,뽈살집,20130321,가정식,제주 제주시 한림읍 한림리 1252-8번지,3_25~50%,1_상위 10% 이하,3_25~50%,0.157025,0.115702,...,0.785124,0.000000,0.132417,0.536,0.464,0.291,0.351,0.186,0.129,0.043
31466,202306,뽈살집,20091224,가정식,제주 서귀포시 서귀동 278-5번지,3_25~50%,2_10~25%,3_25~50%,0.150442,0.176991,...,0.592920,0.097345,0.076570,0.536,0.464,0.298,0.294,0.200,0.160,0.048
37162,202307,뽈살집,20130321,가정식,제주 제주시 한림읍 한림리 1252-8번지,3_25~50%,1_상위 10% 이하,2_10~25%,0.168067,0.151261,...,0.857143,0.008403,0.139501,0.530,0.470,0.288,0.352,0.183,0.132,0.045
39098,202307,뽈살집,20091224,가정식,제주 서귀포시 서귀동 278-5번지,3_25~50%,2_10~25%,3_25~50%,0.105263,0.126316,...,0.705263,0.063158,0.081081,0.539,0.461,0.294,0.290,0.198,0.168,0.050
41351,202308,뽈살집,20130321,가정식,제주 제주시 한림읍 한림리 1252-8번지,3_25~50%,1_상위 10% 이하,3_25~50%,0.211679,0.138686,...,0.839416,0.000000,0.138665,0.527,0.473,0.284,0.348,0.190,0.131,0.046
43345,202308,뽈살집,20091224,가정식,제주 서귀포시 서귀동 278-5번지,3_25~50%,2_10~25%,3_25~50%,0.180000,0.100000,...,0.550000,0.050000,0.081395,0.539,0.461,0.294,0.295,0.197,0.168,0.047
46128,202309,뽈살집,20130321,가정식,제주 제주시 한림읍 한림리 1252-8번지,3_25~50%,2_10~25%,3_25~50%,0.125000,0.115385,...,0.884615,0.000000,0.141892,0.524,0.476,0.287,0.345,0.193,0.134,0.042
46275,202309,뽈살집,20091224,가정식,제주 서귀포시 서귀동 278-5번지,3_25~50%,2_10~25%,3_25~50%,0.090909,0.109091,...,0.690909,0.027273,0.078295,0.542,0.458,0.295,0.304,0.193,0.167,0.042
54605,202310,뽈살집,20130321,가정식,제주 제주시 한림읍 한림리 1252-8번지,3_25~50%,2_10~25%,3_25~50%,0.205882,0.166667,...,0.813725,0.019608,0.145881,0.516,0.484,0.280,0.335,0.197,0.139,0.048
55033,202310,뽈살집,20091224,가정식,제주 서귀포시 서귀동 278-5번지,3_25~50%,2_10~25%,3_25~50%,0.201923,0.086538,...,0.625000,0.038462,0.084421,0.547,0.453,0.286,0.302,0.195,0.175,0.042
58743,202311,뽈살집,20130321,가정식,제주 제주시 한림읍 한림리 1252-8번지,3_25~50%,2_10~25%,3_25~50%,0.188235,0.141176,...,0.823529,0.023529,0.146646,0.515,0.485,0.282,0.329,0.200,0.137,0.051
59998,202311,뽈살집,20091224,가정식,제주 서귀포시 서귀동 278-5번지,3_25~50%,2_10~25%,3_25~50%,0.120879,0.153846,...,0.637363,0.043956,0.089009,0.534,0.466,0.280,0.307,0.196,0.174,0.043
62884,202312,뽈살집,20130321,가정식,제주 제주시 한림읍 한림리 1252-8번지,3_25~50%,2_10~25%,3_25~50%,0.072917,0.125000,...,0.760417,0.010417,0.146341,0.518,0.482,0.281,0.326,0.203,0.137,0.053
66568,202312,뽈살집,20091224,가정식,제주 서귀포시 서귀동 278-5번지,3_25~50%,2_10~25%,3_25~50%,0.083333,0.166667,...,0.601852,0.055556,0.084891,0.536,0.464,0.283,0.313,0.194,0.168,0.043

# 개설일자

In [ ]:
df['개설일자']

0        20110701
1        20050407
2        20120919
3        20130627
4        20220826
           ...
67859    20230630
67860    20210513
67861    20020112
67862    20040109
67863    20200602
Name: 개설일자, Length: 67864, dtype: int64

#업종

In [ ]:
df['업종'].unique()

array(['가정식', '단품요리 전문', '커피', '베이커리', '일식', '치킨', '중식', '분식', '햄버거',
       '양식', '맥주/요리주점', '아이스크림/빙수', '피자', '샌드위치/토스트', '차', '꼬치구이',
       '기타세계요리', '구내식당/푸드코트', '떡/한과', '도시락', '도너츠', '주스', '동남아/인도음식',
       '패밀리 레스토랑', '기사식당', '야식', '스테이크', '포장마차', '부페', '민속주점'],
      dtype=object)

In [ ]:
df['업종'].nunique()

30

#주소
- 중복된 이유 = 기준연월별

In [ ]:
df['주소'].nunique()

8843

# 이용건수비중
- 1구간 : 상위 10%이하
- 2구간 : 10-25%
- 3구간 : 25-50%
- 4구간 : 50-75%
- 5구간 : 75-90%
- 6구간 : 90%초과(하위 10%이하)

In [ ]:
#이용건수구간 수정
df['이용건수구간'] = df['이용건수구간'].replace({'1_상위 10% 이하' : 1,
                                                '2_10~25%' : 2,
                                                '3_25~50%' : 3,
                                                '4_50~75%' : 4,
                                                '5_75~90%' : 5,
                                                '6_90% 초과(하위 10% 이하)' : 6})

In [ ]:
df['이용건수구간'].unique()

array([5, 3, 2, 1, 6, 4])

In [ ]:
#이용금액구간 수정

df['이용금액구간'] = df['이용금액구간'].replace({'1_상위 10% 이하' : 1,
                                                '2_10~25%' : 2,
                                                '3_25~50%' : 3,
                                                '4_50~75%' : 4,
                                                '5_75~90%' : 5,
                                                '6_90% 초과(하위 10% 이하)' : 6})

In [ ]:
df['이용금액구간'].unique()

array([4, 2, 3, 5, 6, 1])

In [ ]:
#건당평균이용금액구간 수정
df['건당평균이용금액구간'] = df['건당평균이용금액구간'].replace({'1_상위 10% 이하' : 1,
                                                '2_10~25%' : 2,
                                                '3_25~50%' : 3,
                                                '4_50~75%' : 4,
                                                '5_75~90%' : 5,
                                                '6_90% 초과(하위 10% 이하)' : 6})

In [ ]:
df['건당평균이용금액구간'].unique()

array([3, 2, 4, 5, 6, 1])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67864 entries, 0 to 67863
Data columns (total 28 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   기준연월           67864 non-null  int64
 1   가맹점명           67864 non-null  object
 2   개설일자           67864 non-null  int64
 3   업종             67864 non-null  object
 4   주소             67864 non-null  object
 5   이용건수구간         67864 non-null  int64
 6   이용금액구간         67864 non-null  int64
 7   건당평균이용금액구간     67864 non-null  int64
 8   월_이용건수비중       67864 non-null  float64
 9   화_이용건수비중       67864 non-null  float64
 10  수_이용건수비중       67864 non-null  float64
 11  목_이용건수비중       67864 non-null  float64
 12  금_이용건수비중       67864 non-null  float64
 13  토_이용건수비중       67864 non-null  float64
 14  일_이용건수비중       67864 non-null  float64
 15  05-11시_이용건수비중  67864 non-null  float64
 16  12-13시_이용건수비중  67864 non-null  float64
 17  14-17시_이용건수비중  67864 non-null  float64
 18  18-22시_이용건수비중  67864 non-null  float64
 19  23-04시_이용건수비중  67864 non-null  float64
 20  현지인_이용건수비중     67864 non-null  float64
 21  남성_이용건수비중      67864 non-null  float64
 22  여성_이용건수비중      67864 non-null  float64
 23  10-20대_회원비중    67864 non-null  float64
 24  30대_회원비중       67864 non-null  float64
 25  40대_회원비중       67864 non-null  float64
 26  50대_회원비중       67864 non-null  float64
 27  60대이상_회원비중     67864 non-null  float64
dtypes: float64(20), int64(5), object(3)
memory usage: 14.5+ MB

In [ ]:
df.head(5)

,기준연월,가맹점명,개설일자,업종,주소,이용건수구간,이용금액구간,건당평균이용금액구간,월_이용건수비중,화_이용건수비중,...,18-22시_이용건수비중,23-04시_이용건수비중,현지인_이용건수비중,남성_이용건수비중,여성_이용건수비중,10-20대_회원비중,30대_회원비중,40대_회원비중,50대_회원비중,60대이상_회원비중
0,202301,통큰돼지,20110701,가정식,제주 제주시 용담이동 2682-9번지 통큰돼지,5,4,3,0.161290,0.032258,...,0.838710,0.000000,0.707763,0.610,0.390,0.103,0.124,0.245,0.387,0.142
1,202301,해변,20050407,단품요리 전문,제주 제주시 애월읍 애월리 410-6번지,3,2,2,0.090909,0.121212,...,0.560606,0.000000,0.230928,0.542,0.458,0.221,0.201,0.195,0.244,0.139
2,202301,한그릇,20120919,단품요리 전문,제주 서귀포시 색달동 2315-1번지 한그릇,3,3,4,0.224719,0.112360,...,0.000000,0.000000,0.347059,0.529,0.471,0.138,0.309,0.342,0.164,0.047
3,202301,협재해녀의집,20130627,가정식,제주 제주시 한림읍 협재리 1459-2번지,3,3,4,0.000000,0.271739,...,0.152174,0.000000,0.016096,0.484,0.516,0.323,0.321,0.209,0.109,0.039
4,202301,까망꼬숑,20220826,단품요리 전문,제주 제주시 노형동 3784-12번지 1층,5,3,2,0.272727,0.121212,...,0.727273,0.090909,0.264463,0.513,0.487,0.412,0.311,0.176,0.076,0.025

In [ ]:
df.columns

Index(['기준연월', '가맹점명', '개설일자', '업종', '주소', '이용건수구간', '이용금액구간', '건당평균이용금액구간',
       '월_이용건수비중', '화_이용건수비중', '수_이용건수비중', '목_이용건수비중', '금_이용건수비중', '토_이용건수비중',
       '일_이용건수비중', '05-11시_이용건수비중', '12-13시_이용건수비중', '14-17시_이용건수비중',
       '18-22시_이용건수비중', '23-04시_이용건수비중', '현지인_이용건수비중', '남성_이용건수비중',
       '여성_이용건수비중', '10-20대_회원비중', '30대_회원비중', '40대_회원비중', '50대_회원비중',
       '60대이상_회원비중'],
      dtype='object')

## 비중 컬럼 %로 바꿈

In [ ]:
ratio_col = ['월_이용건수비중', '화_이용건수비중', '수_이용건수비중', '목_이용건수비중', '금_이용건수비중', '토_이용건수비중',
       '일_이용건수비중', '05-11시_이용건수비중', '12-13시_이용건수비중', '14-17시_이용건수비중',
       '18-22시_이용건수비중', '23-04시_이용건수비중', '현지인_이용건수비중', '남성_이용건수비중',
       '여성_이용건수비중', '10-20대_회원비중', '30대_회원비중', '40대_회원비중', '50대_회원비중',
       '60대이상_회원비중']

df[ratio_col] = df[ratio_col].apply(lambda x: x * 100).round(2)

In [ ]:
df.head()

,기준연월,가맹점명,개설일자,업종,주소,이용건수구간,이용금액구간,건당평균이용금액구간,월_이용건수비중,화_이용건수비중,...,18-22시_이용건수비중,23-04시_이용건수비중,현지인_이용건수비중,남성_이용건수비중,여성_이용건수비중,10-20대_회원비중,30대_회원비중,40대_회원비중,50대_회원비중,60대이상_회원비중
0,202301,통큰돼지,20110701,가정식,제주 제주시 용담이동 2682-9번지 통큰돼지,5,4,3,16.13,3.23,...,83.87,0.00,70.78,61.0,39.0,10.3,12.4,24.5,38.7,14.2
1,202301,해변,20050407,단품요리 전문,제주 제주시 애월읍 애월리 410-6번지,3,2,2,9.09,12.12,...,56.06,0.00,23.09,54.2,45.8,22.1,20.1,19.5,24.4,13.9
2,202301,한그릇,20120919,단품요리 전문,제주 서귀포시 색달동 2315-1번지 한그릇,3,3,4,22.47,11.24,...,0.00,0.00,34.71,52.9,47.1,13.8,30.9,34.2,16.4,4.7
3,202301,협재해녀의집,20130627,가정식,제주 제주시 한림읍 협재리 1459-2번지,3,3,4,0.00,27.17,...,15.22,0.00,1.61,48.4,51.6,32.3,32.1,20.9,10.9,3.9
4,202301,까망꼬숑,20220826,단품요리 전문,제주 제주시 노형동 3784-12번지 1층,5,3,2,27.27,12.12,...,72.73,9.09,26.45,51.3,48.7,41.2,31.1,17.6,7.6,2.5

## 파생변수 best_age 생성
- 가장 비중이 높은 나이

In [ ]:
age_col =  ['10-20대_회원비중', '30대_회원비중', '40대_회원비중', '50대_회원비중', '60대이상_회원비중']
df['best_age'] = df[age_col].idxmax(axis=1)
df['best_age'] = df['best_age'].replace({
    '10-20대_회원비중': '10-20대',
    '30대_회원비중': '30대',
    '40대_회원비중': '40대',
    '50대_회원비중': '50대',
    '60대이상_회원비중': '60대이상'
})


print(df[['best_age']].head())

  best_age
0      50대
1      50대
2      40대
3   10-20대
4   10-20대

In [ ]:
df.head(5)

,기준연월,가맹점명,개설일자,업종,주소,이용건수구간,이용금액구간,건당평균이용금액구간,월_이용건수비중,화_이용건수비중,...,23-04시_이용건수비중,현지인_이용건수비중,남성_이용건수비중,여성_이용건수비중,10-20대_회원비중,30대_회원비중,40대_회원비중,50대_회원비중,60대이상_회원비중,best_age
0,202301,통큰돼지,20110701,가정식,제주 제주시 용담이동 2682-9번지 통큰돼지,5,4,3,16.13,3.23,...,0.00,70.78,61.0,39.0,10.3,12.4,24.5,38.7,14.2,50대
1,202301,해변,20050407,단품요리 전문,제주 제주시 애월읍 애월리 410-6번지,3,2,2,9.09,12.12,...,0.00,23.09,54.2,45.8,22.1,20.1,19.5,24.4,13.9,50대
2,202301,한그릇,20120919,단품요리 전문,제주 서귀포시 색달동 2315-1번지 한그릇,3,3,4,22.47,11.24,...,0.00,34.71,52.9,47.1,13.8,30.9,34.2,16.4,4.7,40대
3,202301,협재해녀의집,20130627,가정식,제주 제주시 한림읍 협재리 1459-2번지,3,3,4,0.00,27.17,...,0.00,1.61,48.4,51.6,32.3,32.1,20.9,10.9,3.9,10-20대
4,202301,까망꼬숑,20220826,단품요리 전문,제주 제주시 노형동 3784-12번지 1층,5,3,2,27.27,12.12,...,9.09,26.45,51.3,48.7,41.2,31.1,17.6,7.6,2.5,10-20대

## 파생변수 best_gender
- 가장 비중이 높은 성별 컬럼

In [ ]:
age_col =  ['남성_이용건수비중',
       '여성_이용건수비중']
df['best_gender'] = df[age_col].idxmax(axis=1)
df['best_gender'] = df['best_gender'].replace({
    '남성_이용건수비중': '남성',
    '여성_이용건수비중': '여성'
})

print(df[['best_gender']].head())

  best_gender
0          남성
1          남성
2          남성
3          여성
4          남성

In [ ]:
df.head(5)

,기준연월,가맹점명,개설일자,업종,주소,이용건수구간,이용금액구간,건당평균이용금액구간,월_이용건수비중,화_이용건수비중,...,현지인_이용건수비중,남성_이용건수비중,여성_이용건수비중,10-20대_회원비중,30대_회원비중,40대_회원비중,50대_회원비중,60대이상_회원비중,best_age,best_gender
0,202301,통큰돼지,20110701,가정식,제주 제주시 용담이동 2682-9번지 통큰돼지,5,4,3,16.13,3.23,...,70.78,61.0,39.0,10.3,12.4,24.5,38.7,14.2,50대,남성
1,202301,해변,20050407,단품요리 전문,제주 제주시 애월읍 애월리 410-6번지,3,2,2,9.09,12.12,...,23.09,54.2,45.8,22.1,20.1,19.5,24.4,13.9,50대,남성
2,202301,한그릇,20120919,단품요리 전문,제주 서귀포시 색달동 2315-1번지 한그릇,3,3,4,22.47,11.24,...,34.71,52.9,47.1,13.8,30.9,34.2,16.4,4.7,40대,남성
3,202301,협재해녀의집,20130627,가정식,제주 제주시 한림읍 협재리 1459-2번지,3,3,4,0.00,27.17,...,1.61,48.4,51.6,32.3,32.1,20.9,10.9,3.9,10-20대,여성
4,202301,까망꼬숑,20220826,단품요리 전문,제주 제주시 노형동 3784-12번지 1층,5,3,2,27.27,12.12,...,26.45,51.3,48.7,41.2,31.1,17.6,7.6,2.5,10-20대,남성

In [ ]:
df.tail(5)

,기준연월,가맹점명,개설일자,업종,주소,이용건수구간,이용금액구간,건당평균이용금액구간,월_이용건수비중,화_이용건수비중,...,현지인_이용건수비중,남성_이용건수비중,여성_이용건수비중,10-20대_회원비중,30대_회원비중,40대_회원비중,50대_회원비중,60대이상_회원비중,best_age,best_gender
67859,202312,미나리,20230630,가정식,제주 제주시 연동 291-24번지 연동,3,2,4,19.20,21.60,...,72.47,54.6,45.4,9.1,26.1,31.3,24.1,9.4,40대,남성
67860,202312,종달리엔심야식당,20210513,가정식,제주 제주시 구좌읍 종달리 1935-1번지 1층,4,4,3,15.00,15.00,...,1.38,25.1,74.9,50.4,35.1,7.7,5.2,1.7,10-20대,여성
67861,202312,경일낙지,20020112,단품요리 전문,제주 제주시 노형동 1291-3번지,2,2,4,17.93,24.14,...,82.51,42.4,57.6,5.4,21.8,37.9,26.3,8.6,40대,여성
67862,202312,흑돼지가있는풍경,20040109,가정식,제주 제주시 노형동 668번지,5,2,1,6.67,0.00,...,19.67,57.4,42.6,10.9,18.8,21.3,30.5,18.5,50대,남성
67863,202312,에이바우트커피삼무공원점,20200602,커피,제주 제주시 연동 260-21번지 1층,1,3,6,10.59,12.57,...,47.12,50.2,49.8,30.6,29.4,18.7,15.4,5.9,10-20대,남성

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67864 entries, 0 to 67863
Data columns (total 30 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   기준연월           67864 non-null  int64
 1   가맹점명           67864 non-null  object
 2   개설일자           67864 non-null  int64
 3   업종             67864 non-null  object
 4   주소             67864 non-null  object
 5   이용건수구간         67864 non-null  int64
 6   이용금액구간         67864 non-null  int64
 7   건당평균이용금액구간     67864 non-null  int64
 8   월_이용건수비중       67864 non-null  float64
 9   화_이용건수비중       67864 non-null  float64
 10  수_이용건수비중       67864 non-null  float64
 11  목_이용건수비중       67864 non-null  float64
 12  금_이용건수비중       67864 non-null  float64
 13  토_이용건수비중       67864 non-null  float64
 14  일_이용건수비중       67864 non-null  float64
 15  05-11시_이용건수비중  67864 non-null  float64
 16  12-13시_이용건수비중  67864 non-null  float64
 17  14-17시_이용건수비중  67864 non-null  float64
 18  18-22시_이용건수비중  67864 non-null  float64
 19  23-04시_이용건수비중  67864 non-null  float64
 20  현지인_이용건수비중     67864 non-null  float64
 21  남성_이용건수비중      67864 non-null  float64
 22  여성_이용건수비중      67864 non-null  float64
 23  10-20대_회원비중    67864 non-null  float64
 24  30대_회원비중       67864 non-null  float64
 25  40대_회원비중       67864 non-null  float64
 26  50대_회원비중       67864 non-null  float64
 27  60대이상_회원비중     67864 non-null  float64
 28  best_age       67864 non-null  object
 29  best_gender    67864 non-null  object
dtypes: float64(20), int64(5), object(5)
memory usage: 15.5+ MB

In [ ]:
df.to_csv('/content/drive/MyDrive/빅콘테스트/01.데이터수집 및 탐색/code/EDA/data/jeju_dining_data.csv', index=False)